### ISSUE TITLE
Wrong info about MikTeX

### ISSUE THREAD

**Issue by pauloney** [Steeven9/USI-LaTeX#1]
The page:
     
    https://steeven9.github.io/USI-LaTeX/html/general_sources.html

says that MikTeX is for Windows xcomputers only, but in reality MiKTeX has distribution for Linux and MacOS as well.

**Comment by Steeven9** [comment]
Hi, 
thank you for your submission! I appreciate the input but this is a university project which is not maintained anymore.

Cheers!
